### ISSUE TITLE
Logging to AWS CloudWatch loses events

### ISSUE THREAD

**Issue by rweinstock** [F5Networks/f5-telemetry-streaming#191]
### Environment
 * Telemetry Streaming Version: 1.26.0
 * BIG-IP Version: 15.1.5

### Summary
When BIG-IP is configured to send LTM and ASM events to AWS CloudWatch via Telemetry Streaming, not all events are being forwarded and the following error appears continuously in /var/log/restnoded/restnoded.log:

`severe: [telemetry.AWS_CloudWatch.f5telemetry_default::My_Consumer] Unable to forward to AWS CloudWatch consumer
Traceback:
InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: 49614506645805016222436204832361823036797491454763075330
    at Request.extractError (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/var/config/rest/iapps/f5-telemetry/node_modules/aws-sdk/lib/event_listeners.js:335:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)`

Refer to attached files:

[ts-declaration.txt](https://github.com/F5Networks/f5-telemetry-streaming/files/8042284/ts-declaration.txt)
[as3-declaration.txt](https://github.com/F5Networks/f5-telemetry-streaming/files/8042285/as3-declaration.txt)
[restnoded.log](https://github.com/F5Networks/f5-telemetry-streaming/files/8042286/restnoded.log)

### Steps To Reproduce
1. Setup a virtual server in BIG-IP that uses LTM and ASM.
2. Setup AWS CloudWatch
3. Modify the attached TS declaration (ts-declaration.txt) according to your AWS CloudWatch setup, and then apply it.
4. Apply the attached AS3 declaration (as3-declaration.txt)
5. Configure local logging of LTM and ASM traffic.
6. Configure logging of LTM and ASM traffic to the "telemetry_traffic_log_profile" and/or "telemetry_asm_security_log_profile" profiles:
7. Generate traffic
8. Observe missing entries in AWS CloudWatch as compared to local traffic logs.
9. Observe errors in /var/log/restnoded/restnoded.log

### Expected Behavior
All traffic should be logged to AWS CloudWatch. No errors should appear in /var/log/restnoded/restnoded.log

### Actual Behavior
Some traffic is not logged to AWS CloudWatch that is otherwise logged locally. Errors can be seen in /var/log/restnoded/restnoded.log

**Comment by dstokesf5** [comment]
Thank you for your feedback. I have added this issue to our internal product backlog as AUTOTOOL-3009.

**Comment by tnamba-f5** [comment]
> Thank you for your feedback. I have added this issue to our internal product backlog as AUTOTOOL-3009.

Hi dstokesf5, is there any target date of when this will be fixed? IHAC running into this issue and needs it fixed asap for compliance.

**Comment by dstokesf5** [comment]
@tnamba-f5 A developer is currently working on this issue. We hope to have a fix for it available in the 1.28.0 release in late April.

**Comment by tnamba-f5** [comment]
Thanks for the info Daniel!

Todd Namba
SE F5 Inc.
720-971-0173
________________________________

**Comment by dstokesf5** [comment]
This issue was resolved as part of the 1.28.0 release of Telemetry Streaming.
