### ISSUE TITLE
CPU spikes

### ISSUE THREAD

**Issue by nvitaly** [F5Networks/f5-telemetry-streaming#21]
##### ISSUE TYPE

 - Bug Report

##### Telemetry Streaming BUILD/ VERSION

f5-telemetry-1.6.0-1.noarch.rpm

##### BIGIP VERSION

Main Package
  Product     BIG-IP
  Version     14.1.0.5
  Build       0.0.5
  Edition     Point Release 5
  Date        Tue May 14 11:15:38 PDT 2019

##### SUMMARY

I start getting CPU spikes on both LTMs where I installed f5-telemetry package. It happening every 20 hours and last around 1-2 hours. CPU reaching 90%

I only enabled systemPoller with interval 60 seconds, Listener (that probably not used, since I am not sending any syslog data in it) and http consumer.

I see following in the log:

restjavad.log:

[I][1075230][30 Sep 2019 13:22:39 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075231][30 Sep 2019 13:22:39 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075232][30 Sep 2019 13:22:39 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075233][30 Sep 2019 13:22:39 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075234][30 Sep 2019 13:22:39 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075235][30 Sep 2019 13:22:39 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075236][30 Sep 2019 13:22:39 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075237][30 Sep 2019 13:22:39 UTC][ProcessManager] Maximum child processes of 3 has been reached
[WARNING][1075238][30 Sep 2019 13:22:56 UTC][8100/shared/iapp/build-package BuildRpmTaskCollectionWorker] Failed to execute the build command 'rpmbuild -bb --define '_tmppath /shared/tmp' --define 'main /var/config/rest/iapps/f5-telemetry' --define '_topdir /var/config/rest/node/tmp' '/var/config/rest/node/tmp/12611861-b874-482d-bf9c-9d51a8be49c7.spec'',  Threw:com.f5.rest.workers.shell.CommandExecuteException: Command execution process killed
        at com.f5.rest.workers.shell.ShellExecutor.finishExecution(ShellExecutor.java:282)
        at com.f5.rest.workers.shell.ShellExecutor.access$000(ShellExecutor.java:34)
        at com.f5.rest.workers.shell.ShellExecutor$1.onProcessFailed(ShellExecutor.java:321)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:203)
        at java.lang.Thread.run(Thread.java:748)

[I][1075242][30 Sep 2019 13:23:35 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075243][30 Sep 2019 13:23:35 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075244][30 Sep 2019 13:23:35 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075245][30 Sep 2019 13:23:35 UTC][ProcessManager] Maximum child processes of 3 has been reached
[I][1075246][30 Sep 2019 13:23:35 UTC][ProcessManager] Maximum child processes of 3 has been reached

But time does not match with CPU spikes.

I don't see anything interesting in var/log/restnoded/restnoded.log

Looks like some CPU heavy process got scheduled periodically. 
 

##### STEPS TO REPRODUCE

```json
{
    "message": "success",
    "declaration": {
        "class": "Telemetry",
        "My_System": {
            "class": "Telemetry_System",
            "systemPoller": {
                "interval": 60,
                "enable": true,
                "trace": false,
                "actions": [
                    {
                        "setTag": {
                            "tenant": "`T`",
                            "application": "`A`"
                        },
                        "enable": true
                    }
                ]
            },
            "enable": true,
            "trace": false,
            "host": "localhost",
            "port": 8100,
            "protocol": "http"
        },
        "My_Listener": {
            "class": "Telemetry_Listener",
            "port": 6514,
            "enable": true,
            "trace": false,
            "match": "",
            "actions": [
                {
                    "setTag": {
                        "tenant": "`T`",
                        "application": "`A`"
                    },
                    "enable": true
                }
            ]
        },
        "My_Consumer": {
            "class": "Telemetry_Consumer",
            "type": "Generic_HTTP",
            "host": "x.x.x.x",
            "protocol": "http",
            "port": 5000,
            "path": "/test",
            "method": "POST",
            "headers": [
                {
                    "name": "content-type",
                    "value": "application/json"
                }
            ],
            "enable": true,
            "trace": false
        },
        "schemaVersion": "1.6.0"
    }
}
```

##### EXPECTED RESULTS
no cpu spikes :)

##### ACTUAL RESULTS

cpu spikes

**Comment by nvitaly** [comment]
my declaration JON looks like:



{
    "class": "Telemetry",
    "My_System": {
        "class": "Telemetry_System",
        "systemPoller": {
            "interval": 60
        }
    },
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514
    },


    "My_Consumer": {
        "class": "Telemetry_Consumer",
        "type": "Generic_HTTP",
        "host": "x.x.x.x",
        "protocol": "http",
        "port": 5000,
        "path": "/test",
        "method": "POST",
        "headers": [
            {
                "name": "content-type",
                "value": "application/json"
            }
        ]
    }

}

**Comment by nvitaly** [comment]
just an update, the process that leading during CPUspikes is tmm.0

**Comment by dstokesf5** [comment]
@nvitaly Just to confirm, you are not seeing the CPU spike when Telemetry Streaming is not installed on the BIG-IP, right? If you start removing parts of the declaration, such as the consumer, or listener, do you see the CPU spike go away?

**Comment by nvitaly** [comment]
I have two separate LTMs, both did not have spikes previously and now got very visible one every 20 hours.

I removed the plugin from one of them to see if it help but need to wait. I will try to disable declarations one by one. I will take a couple of days probably.

I will update you.

**Comment by nvitaly** [comment]
the issue with CPU start happening when I enable:

 "My_System": {
        "class": "Telemetry_System",
        "systemPoller": {
            "interval": 60
        }
    }    

If I remove it, it stop happening.

CPU spike is high and long (99% for a few hours) there is no way we can enable this in production. If you need help with investigating let me know. but the issues is easy to replicate.

Thank you

**Comment by dstokesf5** [comment]
Thank you for the additional information. I have created AT-852 in our internal product backlog to track this issue.

**Comment by dstokesf5** [comment]
@nvitaly We could use some additional information in order to help us reproduce this issue:
* How many CPUs and how much RAM do your systems have
* Are you running these LTMs in a virtual environment, if so which one?
* How many configuration objects (e.g. virtuals, pools, nodes) are on these devices?
* Do you still see this issue with the latest release of TS?

**Comment by dstokesf5** [comment]
Closing for inactivity.
