### ISSUE TITLE
Cannot trust the consumer's CA certificate with Telemetry

### ISSUE THREAD

**Issue by SankoZaha** [F5Networks/f5-telemetry-streaming#218]
### Is your feature request related to a problem? 
The Consumer configuration in Telemetry Streaming doesn't allow the Consumer's CA root certificate to be trusted.
Only the "allowSelfSignedCert" parameter of the "Telemetry_Consumer" class allows to bypass this verification, which is too permissive.

```
(/var/log/restnoded/restnoded.log) : 
Traceback:
Error: HTTP error: Error: self signed certificate in certificate chain
    at Request.request.(anonymous function) [as _callback] (/var/config/rest/iapps/f5-telemetry/lib/utils/requests.js:181:24)
    at self.callback (/var/config/rest/iapps/f5-telemetry/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/var/config/rest/iapps/f5-telemetry/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Describe the solution you'd like
Having a parameter in the "Telemetry_Consumer" class allowing to trust the consumer's CA root certificate while setting "allowSelfSignedCert" to False.

### Describe alternatives you've considered
Create a VS between Telemetry Streaming and the consumer to take advantage of its features, including trusting the Splunk CA certificate via the SSL server profile but this alternative is not practical and ideal.

**Comment by dstokesf5** [comment]
You can provide additional CA certificates to the `restnoded` process that runs Telemetry Streaming. To do this, you need to modify `/etc/bigstart/scripts/restnoded` to export a new value for the `NODE_EXTRA_CA_CERTS` environment variable. Below is an example of exporting this environment variable.

```bash
#!/bin/sh

service=restnoded

# First argument passed to these scripts is the number of starts
start_cnt=$1

# load common functions and clear down indicators
. /usr/lib/bigstart/functions
clear_down ${service}
...
export NODE_PATH=/usr/lib/node_modules
export NODE_EXTRA_CA_CERTS=/config/ssl/ssl.crt/ca-bundle.crt
...
```

I understand that this is a bit of a complex process, but does it resolve your certificate issues? If it does, we can look into ways to make this simpler.
