### ISSUE TITLE
Add support for Viprion systems

### ISSUE THREAD

**Issue by strantalis** [F5Networks/f5-telemetry-streaming#27]
##### ISSUE TYPE

 - Bug Report

##### Telemetry Streaming BUILD/ VERSION

```
Tried
f5-telemetry-1.7.0-1.noarch.rpm
f5-telemetry-1.6.0-1.noarch.rpm
f5-telemetry-1.5.0-1.noarch.rpm
```

##### BIGIP VERSION

```
Version     13.1.0.8
```

##### SUMMARY

```
The telemetry service is throwing stack traces "TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m". Which I believe is causing no data to be collected.
```

##### STEPS TO REPRODUCE

```
{
    "class": "Telemetry",
    "My_System": {
        "class": "Telemetry_System",
        "allowSelfSignedCert": "true",
        "systemPoller": {
            "interval": 60
        }
    },
    "My_Listener": {
        "class": "Telemetry_Listener",
        "port": 6514
    },
    "My_Consumer": {
        "class": "Telemetry_Consumer",
        "allowSelfSignedCert": "true",
        "type": "Splunk",
        "host": "example-hec.splunk.com",
        "index": "f5_index",
        "protocol": "https",
        "port": 443,
        "passphrase": {
            "cipherText": "XXXXXXX-XXXX-XXXXX-XXX-XXXXXXXXX"
        }
    }
}
```

##### EXPECTED RESULTS

To start and see data flowing to the consumer.

##### ACTUAL RESULTS

```
on, 28 Oct 2019 17:06:45 GMT - severe: [telemetry] Error: SystemStats._processProperty: cpu (/mgmt/tm/sys/host-info::sys/host-info/0::sys/hostInfo/0/cpuInfo): Error: runCustomFunction failed: TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m
Mon, 28 Oct 2019 17:06:45 GMT - severe: [telemetry] Error: SystemStats.collect: Error: runCustomFunction failed: TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m
Mon, 28 Oct 2019 17:06:45 GMT - severe: [telemetry] systemPoller:safeProcess unhandled exception in promise-chain
Traceback:
Error: runCustomFunction failed: TypeError: Cannot use 'in' operator to search for 'oneMinAvgSystem' in m
    at Object._runCustomFunction (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:168:19)
    at /var/config/rest/iapps/f5-telemetry/lib/normalize.js:561:36
    at Array.forEach (native)
    at /var/config/rest/iapps/f5-telemetry/lib/normalize.js:556:39
    at Array.forEach (native)
    at Object.data (/var/config/rest/iapps/f5-telemetry/lib/normalize.js:530:35)
    at SystemStats._resolveConditional.SystemStats._preprocessProperty.SystemStats._processData.renameKeysIndex [as _processData] (/var/config/rest/iapps/f5-telemetry/lib/systemStats.js:217:60)
    at /var/config/rest/iapps/f5-telemetry/lib/systemStats.js:273:40
    at process._tickCallback (node.js:438:9)
```

**Comment by dstokesf5** [comment]
Are you running Telemetry Streaming on a Viprion system?

**Comment by strantalis** [comment]
Yes we are.

**Comment by dstokesf5** [comment]
Unfortunately Telemetry Streaming does not currently work on Viprion systems. We have internal product backlog item AUTOTOOL-853 to track adding support for Viprion systems.

**Comment by danielitus** [comment]
Hello! We have a running Viprion in HA, with a big configuration 9,5M bigip.conf, some numbers are:  ~ 300 VS, ~ 2000 pools, ~ 5000 nodes, ~ 1900 irules. The config is always changing (around 30 changes p/m), the most changes are, disable pool member and enable pool member. Do you think that MCPD with all this configuration (and changes) will endure the poller system?
Saying this, we are looking forward to get TS support for Viprion.

**Comment by dstokesf5** [comment]
Support for Viprion systems was added as part of the 1.10.0 release. Closing this issue. If you are still experiencing a problem, please reopen this issue or create a new one.
