### ISSUE TITLE
F5 stops sending logs to Azure Log Analytics when the F5 server reboots

### ISSUE THREAD

**Issue by cnad001** [F5Networks/f5-telemetry-streaming#48]
### Environment
 * Telemetry Streaming Version: 1.11.0.1 (f5-telemetry-1.11.0-1.noarch.rpm)
 * BIG-IP Version: 15.0.100000

### Summary
F5 server stops sending logs to Azure Log Analytics after an F5 server reboot. 

### Steps To Reproduce
Configure telemetry on F5 with the following JSON. The logs start getting transmitted to Azure log analytics. Reboot the server and the logs stop transmitting to Log Analytics
1. Submit the following declaration:
```json
"telemetry": {
                 "class": "Pool",
                 "members": [
                   {
                   "enable": true,
                   "serverAddresses": [
                       "255.255.255.254"
                       ],
                   "servicePort": 6514
                   }
                 ],
                   "monitors": [
                      {
                           "bigip": "/Common/tcp"
                       }
                 ]
                },
            "telemetry_local_rule": {
              "remark": "Only required when TS is a local listener",
              "class": "iRule",
              "iRule": "when CLIENT_ACCEPTED {\n  node 127.0.0.1 6514\n}"
            },
            "telemetry_local": {
              "remark": "Only required when TS is a local listener",
              "class": "Service_TCP",
              "virtualAddresses": [
                "255.255.255.254"
              ],
              "virtualPort": 6514,
              "iRules": [
              "telemetry_local_rule"
              ]
            },
            "telemetry_hsl": {
              "class": "Log_Destination",
              "type": "remote-high-speed-log",
              "protocol": "tcp",
              "pool": {
                "use": "telemetry"
              }
            },
            "telemetry_formatted": {
              "class": "Log_Destination",
              "type": "splunk",
              "forwardTo": {
                "use": "telemetry_hsl"
              }
            },
            "telemetry_publisher": {
              "class": "Log_Publisher",
              "destinations": [
                {
                  "use": "telemetry_formatted"
                }
              ]
            }
        }
```

2. Observe the following error response:
```
Following error is captured in /var/log/restnoded/restnoded.log
Fri, 24 Apr 2020 14:26:44 GMT - severe: [telemetry.Azure_Log_Analytics.My_Consumer] Unable to forward to Azure Log Analytics consumer.
Traceback:
Error: Bad status code: 403 Forbidden for https://0e58b1e7-e783-40b4-aea3-341ccc4b9221.ods.opinsights.azure.com/api/logs?api-version=2016-04-01
    at Request.request.(anonymous function) [as _callback] (/var/config/rest/iapps/f5-telemetry/lib/util.js:982:32)
    at Request.self.callback (/var/config/rest/iapps/f5-telemetry/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/config/rest/iapps/f5-telemetry/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/config/rest/iapps/f5-telemetry/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Expected Behavior
The logs should continue to flow to log analytics

**Comment by dstokesf5** [comment]
Thank you for reporting this. I have copied it to our internal product backlog as AUTOTOOL-1555.

**Comment by dstokesf5** [comment]
@cnad001 It looks like your declaration in step one is incomplete, and is an AS3 declaration. Can you provide the rest of that AS3 declaration, as well as the TS declaration to make these easier for the developers to reproduce?

**Comment by cnad001** [comment]
Hi Daniel,

Here is the path to AS3 declaration.

https://github.com/thomsonjames/AttAzureBastion/blob/master/F5_bastion_config-v5-generic.json

I use the following command to setup telemetry.

token=$(curl -X POST -s -k \
  https://$localIpAddress/mgmt/shared/authn/login \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d "{
    \"username\":\"$apiUser\",
    \"password\":\"$adminPasswordOrKey\",
    \"loginProviderName\":\"tmos\"
}" | jq -r '.token.token')

curl -X POST -s -k \
  https://$localIpAddress/mgmt/shared/telemetry/declare \
  -H 'Content-Type: application/json' \
  -H "X-F5-Auth-Token: $token" \
  -H 'cache-control: no-cache' \
  -d "{
    \"class\": \"Telemetry\",
    \"My_System\": {
        \"class\": \"Telemetry_System\",
        \"systemPoller\": {
            \"interval\": 60
        }
    },
    \"My_Listener\": {
        \"class\": \"Telemetry_Listener\",
        \"port\": 6514
    },
    \"My_Consumer\": {
        \"class\": \"Telemetry_Consumer\",
        \"type\": \"Azure_Log_Analytics\",
        \"workspaceId\": \"$workspaceId\",
        \"passphrase\": {
          \"cipherText\": \"$cipherText\"
        }
    }
}"


Thanks,
Chetan Nadgonde
Public Cloud Infrastructure and Technology, AT&T Services
+1 (972) 202-6241

**Comment by dstokesf5** [comment]
Thank you for the additional information, I will pass this along to the developers.

**Comment by kaustriaf5** [comment]
Hi @cnad001  I've tried manually restarting the services as well as server reboot, but I have been unable to repro this. I have some follow up questions:
- Does this happen for you even with a new instance?
- Does this repro with subsequent reboots?
- Is your VM instance on Azure? If so, is your Log Analytics workspace in the same resource group/subscription as your instance?
- Do you happen to have a larger snippet of the logs before and after the error you noted above (with sensitive info redacted)?

**Comment by dstokesf5** [comment]
Closing for inactivity. If you are still experiencing a problem, feel free to reopen this ticket and respond to the questions above. Or create a new ticket if you have new information.
